import Head from "next/head";
// import WelcomeSection from "../components/sections/Welcome";
import ProjectsSection from "../components/sections/Projects";
export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Altay Simsek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <ProjectsSection />
      </main>

      <footer></footer>
    </div>
  );
}
